apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
  POSTGRES_USER: {{ .Values.postgres.credentials.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
  DATABASE_URL: "postgres://{{ .Values.postgres.credentials.username }}:{{ .Values.postgres.credentials.password }}@{{ .Values.postgres.name }}:{{ .Values.postgres.port }}/{{ .Values.postgres.credentials.database }}?sslmode=disable"
